

server:
  port: 9000

spring:
  application:
    name: order-service
  redis:
    host: 192.168.85.156
    port: 6379
    password: myreids
    redisson:
      config: classpath:redisson.yaml

eureka:
  instance:
    hostname: localhost
    metadata-map:
      version: current
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
#    registryFetchIntervalSeconds: 1
#    leaseRenewalIntervalInSeconds: 1

ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    enabled: false

